wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704269325.582626
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
